import {
  boolean,
  index,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const games = pgTable("games", {
  id: serial().primaryKey(),
  title: text().notNull().unique(),
  category: text().notNull().default("Action"),
  imageUrl: text("image_url").notNull().default(""),
  salePrice: numeric("sale_price", { precision: 10, scale: 2 }).notNull(),
  originalPrice: numeric("original_price", { precision: 10, scale: 2 }).notNull(),
  discount: integer().notNull().default(0),
  rating: integer().notNull().default(5),
  badge: text(),
  description: text().notNull().default(""),
  steamUrl: text("steam_url"),
  isFeatured: boolean("is_featured").notNull().default(false),
  inStock: boolean("in_stock").notNull().default(true),
  isActive: boolean("is_active").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const orders = pgTable("orders", {
  id: serial().primaryKey(),
  orderRef: text("order_ref").notNull().unique(),
  customerName: text("customer_name").notNull(),
  instagram: text().notNull(),
  email: text(),
  telegram: text(),
  gameName: text("game_name").notNull(),
  expectedAmount: numeric("expected_amount", { precision: 10, scale: 2 }).notNull(),
  submittedAmount: numeric("submitted_amount", { precision: 10, scale: 2 }).notNull(),
  screenshotFile: text("screenshot_file"),
  screenshotHash: text("screenshot_hash"),
  steamUsername: text("steam_username"),
  steamPassword: text("steam_password"),
  paymentMethod: text("payment_method").notNull().default("upi"),
  paymentStatus: text("payment_status").notNull().default("pending_verification"),
  failureReason: text("failure_reason"),
  upiTransactionId: text("upi_transaction_id"),
  ocrAmount: numeric("ocr_amount", { precision: 10, scale: 2 }),
  ocrDate: text("ocr_date"),
  ocrTime: text("ocr_time"),
  ocrReceiver: text("ocr_receiver"),
  ocrRawStatus: text("ocr_raw_status"),
  verificationMode: text("verification_mode"),
  verificationResult: text("verification_result"),
  fraudDetected: boolean("fraud_detected").notNull().default(false),
  submittedAt: timestamp("submitted_at").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  verifiedAt: timestamp("verified_at"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => ({
  statusIdx: index("orders_payment_status_idx").on(table.paymentStatus),
  orderRefIdx: uniqueIndex("orders_order_ref_uidx").on(table.orderRef),
  transactionIdx: uniqueIndex("orders_upi_transaction_id_uidx").on(table.upiTransactionId),
  screenshotHashIdx: uniqueIndex("orders_screenshot_hash_uidx").on(table.screenshotHash),
  instagramIdx: index("orders_instagram_idx").on(table.instagram),
}));

export const ocrTokenUses = pgTable("ocr_token_uses", {
  jti: text().primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
  id: serial().primaryKey(),
  orderId: integer("order_id").references(() => orders.id),
  orderRef: text("order_ref").notNull(),
  transactionId: text("transaction_id"),
  customerName: text("customer_name").notNull(),
  verificationResult: text("verification_result").notNull(),
  adminAction: text("admin_action"),
  details: text(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
